accounts:
  - name: testvalidator
    coins: ["100000000basecro"]
  - name: community
    coins: ["10000000000basecro"]
  - name: ecosystem
    coins: ["20000000000basecro"]
  - name: reserve
    coins: ["20000000000basecro"]
  - name: launch
    coins: ["10000000000basecro"]
validator:
  name: testvalidator
  staked: "100000000basecro"
