chain_id: chainmaind
validators:
  - coins: 10cro
    staked: 10cro
    # name: moniker_name #default node{i}
  - coins: 10cro
    staked: 10cro
accounts:
  - name: community
    coins: 100cro
  - name: ecosystem
    coins: 200cro
  - name: reserve
    coins: 200cro
    vesting: "1d"
  - name: launch
    coins: 100cro
genesis:
  app_state:
    staking:
      params:
        unbonding_time: "10s"
