validators:
  - coins: 10cro
    staked: 10cro
  - coins: 10cro
    staked: 10cro
accounts:
  - name: community
    coins: 100cro
  - name: ecosystem
    coins: 200cro
  - name: reserve
    # FIXME change to 200cro after coin conversion fixed
    coins: 20000000000basecro
    vesting: "60s"
  - name: launch
    coins: 100cro
genesis:
 app_state:
   staking:
     params:
       unbonding_time: "10s"
