name: Go Nancy

on:
    pull_request:
    push:
      branches:
        - master
        - release/**
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: WriteGoList
      run: go list -json -m all > go.list
    - name: Nancy
      uses: sonatype-nexus-community/nancy-github-action@master