name: nix flow
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      if: github.ref == 'refs/heads/master'
      with:
        name: crypto-com
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use crypto-com
      if: github.ref != 'refs/heads/master'
    - run: nix run nixpkgs.python3Packages.flake8 -c flake8 --max-line-length 88 --extend-ignore E203 integration-tests/tests pystarport
    - run: nix run nixpkgs.python3Packages.black -c black --check --diff integration-tests/tests pystarport
    - run: nix-shell --run "isort -c --diff -rc integration-tests/tests pystarport"
    - run: nix-shell --run "python -mpytest -v integration-tests/tests"
    - run: nix-build -o pystarportImage -A pystarportImage docker.nix
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: docker_image
        path: ./pystarportImage
