name: nix flow
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      if: github.ref == 'refs/heads/master'
      with:
        name: crypto-com
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use crypto-com
      if: github.ref != 'refs/heads/master'
    - run: nix-shell integration_tests/shell.nix --run "make lintpy"
    - run: make nix-integration-test
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: integration_tests
    - run: make pystarportImage
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: docker_image
        path: ./pystarportImage
