name: nix flow
on:
  pull_request:
  push:
    branches:
      - master
      - release/**
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      if: github.ref == 'refs/heads/master'
      with:
        name: crypto-com
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use crypto-com
      if: github.ref != 'refs/heads/master'
    - name: Lint python
      run: nix-shell integration_tests/shell.nix --run "make lintpy"
    - name: Run integration tests
      run: make nix-integration-test
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: integration_tests
    - name: Publish docker image
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      run: |
        nix-build -A pystarportImage docker.nix
        IMAGE=$(docker load < result)
        IMAGE=${IMAGE#Loaded image: }
        if [ "$GITHUB_REF" == "refs/tags/*" ]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG="latest"
        fi
        TARGET="docker.pkg.github.com/${{ github.repository }}/chain-main-pystarport:$TAG"
        docker tag $IMAGE $TARGET
        docker login -u "$GITHUB_ACTOR" -p "${{ github.token }}" docker.pkg.github.com
        docker push $TARGET
        echo "pushed: $TARGET"
